#!/bin/bash

set -e

# Parse image name
tagStart=$(expr index "${IMAGE_NAME}" :)
#repoName=${IMAGE_NAME:0:tagStart-1}

echo "Post-push processing image: ${IMAGE_NAME}. Tag: ${IMAGE_NAME:tagStart}. Cache tag:  ${CACHE_TAG}."
echo "Current commit=${SOURCE_COMMIT}"
echo "Current branch=${SOURCE_BRANCH}"

#Take commit sha (or git tag if available)
for tag in ${SOURCE_COMMIT} $(git tag -l --points-at HEAD | sed 's/^v//' || echo ""); do
      echo "Additional tag: ${tag##*/}"
      docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${tag##*/}
      docker push ${DOCKER_REPO}:${tag##*/}
      CTAG="${IMAGE_NAME:tagStart}_${tag##*/}"
      echo "Additional compound tag: ${CTAG}"
      docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${CTAG}
      docker push ${DOCKER_REPO}:${CTAG}
 done